```yaml
name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Add upstream repository
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_URL }}
          
      - name: Fetch upstream changes
        run: |
          git fetch upstream
          
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main
          
      - name: Push changes
        run: |
          git push origin main
```
